/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'sqlin' at '4/9/17 9:52 AM' with Gradle 3.1
 *
 * @author sqlin, @date 4/9/17 9:52 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
